package notes

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

type MeetingMeta struct {
	SourceFile     string
	ProcessedAt    time.Time
	Duration       string
	TranscriptFile string
	Version        string
}

func Heuristic(transcript string, meta MeetingMeta) string {
	segments := splitSegments(transcript)
	topics := extractTopics(segments, 8)
	decisions := findCandidates(segments, []string{
		"we decided",
		"decision",
		"we agreed",
		"the plan is",
		"we are going with",
		"we're going with",
	})
	actions := findCandidates(segments, []string{
		"i will",
		"i'll",
		"we will",
		"we need to",
		"follow up",
		"action item",
		"can you",
		"please",
		"by friday",
		"by monday",
		"by tuesday",
		"by wednesday",
		"by thursday",
		"next week",
	})
	questions := findQuestions(segments)
	dates := findCandidates(segments, []string{
		"by monday",
		"by tuesday",
		"by wednesday",
		"by thursday",
		"by friday",
		"by next",
		"next week",
		"tomorrow",
		"deadline",
		"follow-up",
		"follow up",
	})

	var b strings.Builder
	b.WriteString("# Meeting Notes\n\n")
	b.WriteString("## Source\n")
	fmt.Fprintf(&b, "- Recording: %s\n", filepath.Base(meta.SourceFile))
	if !meta.ProcessedAt.IsZero() {
		fmt.Fprintf(&b, "- Processed: %s\n", meta.ProcessedAt.Format(time.RFC3339))
	}
	if meta.Duration != "" {
		fmt.Fprintf(&b, "- Duration: %s\n", meta.Duration)
	}
	if meta.TranscriptFile != "" {
		fmt.Fprintf(&b, "- Transcript: %s\n", meta.TranscriptFile)
	}
	if meta.Version != "" {
		fmt.Fprintf(&b, "- Generated by: meeting-transcriber %s\n", meta.Version)
	}
	b.WriteString("\n")

	b.WriteString("## Review status\n")
	b.WriteString("Draft generated from machine transcription. Human review required.\n\n")

	b.WriteString("## Executive summary\n")
	b.WriteString(executiveSummary(segments))
	b.WriteString("\n\n")

	writeBullets(&b, "## Topics discussed", topics, "- No strong repeated topics detected.")
	writeBullets(&b, "## Decisions", prefixCandidate(decisions), "- No candidate decisions detected.")
	writeActionItems(&b, actions)
	writeBullets(&b, "## Open questions", prefixCandidate(questions), "- No candidate open questions detected.")
	writeBullets(&b, "## Dates, deadlines, and follow-ups mentioned", prefixCandidate(dates), "- No candidate dates, deadlines, or follow-ups detected.")

	b.WriteString("## Full transcript\n")
	if meta.TranscriptFile == "" {
		b.WriteString("See `transcript.txt`.\n")
	} else {
		fmt.Fprintf(&b, "See `%s`.\n", meta.TranscriptFile)
	}
	return b.String()
}

func executiveSummary(segments []string) string {
	if len(segments) == 0 {
		return "Transcript was empty or unavailable, so no summary could be inferred."
	}
	var chosen []string
	for _, segment := range segments {
		if wordCount(segment) < 5 {
			continue
		}
		chosen = append(chosen, segment)
		if len(chosen) == 2 {
			break
		}
	}
	if len(chosen) == 0 {
		return "Transcript content was too short for a reliable summary."
	}
	summary := strings.Join(chosen, " ")
	if len(summary) > 500 {
		summary = summary[:500] + "..."
	}
	return "Candidate summary: " + summary
}

var sentenceSplit = regexp.MustCompile(`[.!?\n\r]+`)

func splitSegments(transcript string) []string {
	raw := sentenceSplit.Split(transcript, -1)
	segments := make([]string, 0, len(raw))
	for _, part := range raw {
		part = normalizeSpace(part)
		if part == "" {
			continue
		}
		segments = append(segments, part)
	}
	return segments
}

func normalizeSpace(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func findCandidates(segments []string, phrases []string) []string {
	var out []string
	for _, segment := range segments {
		lower := strings.ToLower(segment)
		for _, phrase := range phrases {
			if strings.Contains(lower, phrase) {
				out = appendUniqueLimited(out, cleanBullet(segment), 8)
				break
			}
		}
	}
	return out
}

func findQuestions(segments []string) []string {
	var out []string
	for _, segment := range segments {
		lower := strings.ToLower(segment)
		if strings.Contains(lower, "question is") ||
			strings.Contains(lower, "need to find out") ||
			strings.Contains(lower, "not sure") {
			out = appendUniqueLimited(out, cleanBullet(segment), 8)
		}
	}
	return out
}

func cleanBullet(s string) string {
	s = normalizeSpace(s)
	if len(s) > 240 {
		s = s[:240] + "..."
	}
	return s
}

func appendUniqueLimited(values []string, value string, limit int) []string {
	for _, existing := range values {
		if strings.EqualFold(existing, value) {
			return values
		}
	}
	if len(values) >= limit {
		return values
	}
	return append(values, value)
}

func prefixCandidate(values []string) []string {
	out := make([]string, len(values))
	for i, value := range values {
		out[i] = "Candidate: " + value
	}
	return out
}

func writeBullets(b *strings.Builder, heading string, values []string, empty string) {
	b.WriteString(heading)
	b.WriteString("\n")
	if len(values) == 0 {
		b.WriteString(empty)
		b.WriteString("\n\n")
		return
	}
	for _, value := range values {
		fmt.Fprintf(b, "- %s\n", value)
	}
	b.WriteString("\n")
}

func writeActionItems(b *strings.Builder, values []string) {
	b.WriteString("## Action items\n")
	if len(values) == 0 {
		b.WriteString("- [ ] No candidate action items detected.\n\n")
		return
	}
	for _, value := range values {
		fmt.Fprintf(b, "- [ ] Candidate: %s - Owner: Unknown - Due: Unknown\n", value)
	}
	b.WriteString("\n")
}

var wordPattern = regexp.MustCompile(`[A-Za-z][A-Za-z'-]{2,}`)

func extractTopics(segments []string, limit int) []string {
	counts := map[string]int{}
	for _, segment := range segments {
		words := wordPattern.FindAllString(strings.ToLower(segment), -1)
		for _, word := range words {
			word = strings.Trim(word, "'-")
			if len(word) < 4 || stopWords[word] {
				continue
			}
			counts[word]++
		}
	}
	type pair struct {
		Word  string
		Count int
	}
	var pairs []pair
	for word, count := range counts {
		if count < 2 {
			continue
		}
		pairs = append(pairs, pair{Word: word, Count: count})
	}
	sort.Slice(pairs, func(i, j int) bool {
		if pairs[i].Count == pairs[j].Count {
			return pairs[i].Word < pairs[j].Word
		}
		return pairs[i].Count > pairs[j].Count
	})
	if len(pairs) > limit {
		pairs = pairs[:limit]
	}
	topics := make([]string, 0, len(pairs))
	for _, pair := range pairs {
		topics = append(topics, fmt.Sprintf("%s (%d mentions)", pair.Word, pair.Count))
	}
	return topics
}

func wordCount(s string) int {
	return len(strings.Fields(s))
}

var stopWords = map[string]bool{
	"about": true, "after": true, "again": true, "also": true, "and": true, "are": true,
	"because": true, "been": true, "being": true, "between": true, "but": true, "can": true,
	"could": true, "did": true, "does": true, "doing": true, "for": true, "from": true,
	"going": true, "had": true, "has": true, "have": true, "how": true, "into": true,
	"just": true, "like": true, "more": true, "need": true, "not": true, "now": true,
	"our": true, "out": true, "over": true, "really": true, "right": true, "should": true,
	"that": true, "the": true, "their": true, "them": true, "then": true, "there": true,
	"these": true, "they": true, "this": true, "through": true, "today": true, "was": true,
	"we": true, "were": true, "what": true, "when": true, "where": true, "which": true,
	"with": true, "would": true, "you": true, "your": true,
}
